### ISSUE TITLE
TP 26/06 2 

### ISSUE THREAD

**Issue by nicomr70** [nicomr70/java-Tom#4]
Tu doit faire le TP  "Heritage et classe Object".

**Comment by TomFrances** [comment]
Pas de soucis particulier

**Comment by nicomr70** [comment]
@FrancesTomUGA voici ta correction
* dans le fichier **Humain.java**
il vaut mieux appeler tous de suite le setter avec 18 que rappeler ```this(18)``` car tu fait moins d'appel.
* du coup ça donne ça : 
```java
public Humain() {
		setAge(18);		//je mets l'age à 18 ans par défaut
	}
```
* sinon un jolie code ! 
# note : 19/20
