### ISSUE TITLE
Prochain TP avec des collections

### ISSUE THREAD

**Issue by nicomr70** [nicomr70/java-Tom#6]
tu dois faire le TP "Bataille On joue avec les Collections" .

**Comment by TomFrances** [comment]
Fier de dire que j'ai terminé ! xD à priori ça marche bien

**Comment by nicomr70** [comment]
@FrancesTomUGA voici ta correction.
## dans le fichier **Carte.java** : 
  -  tu n'as pas besoin d'appeler ```super()``` dans le constructeur car ici tu fait un ```implements``` et non un ```extend```
 ## dans le fichier **Joueur.java** : 
  - dans la méthode **joue()** tu n'a pas besoin de créer une carte null , et de voir si elle existe, tu n'a pas assez lu la doc et donc tu n'a pas vue que ```deck.pollFirst();```renvoie null si le deck est vide **ici ton erreur est d'avoir utiliser une collection sans savoir ses avantages.**
  - donc ça donnerai ça :
```java
	public Carte joue() {
		return deck.pollFirst();
	}
```
  - ensuite dans la méthode **printDeck()** pourquoi utiliser un itérator alors que ArrayDeck est iterable , encore une fois tu n'a pas lu correctement la doc de la collection que tu a utilisé.
  - donc ça donnerai ça : 
```java 
public void printDeck() {
		System.out.println("Cartes du deck de " + getNom());
		for(Carte it : deck) {
			System.out.println(it.toString());
		}
	}
```
## dans le fichier **Jeu.java** : 
⚠️ dans le méthode **initialiseJeuDeCartes()** ne pas faire de **L'itératif** ici tu doit utiliser des boucles ```for```
* de cette manière : 
```java
private void initialiseJeuDeCartes() {
		jeuDeCartes = new ArrayList<>();
		for(Couleur c : Couleur.values()) {
			for(Valeur v : Valeur.values()) {
				jeuDeCartes.add(new Carte(c, v));
			}
		}
	}
```
* dans la méthode **joueurJoue(int joueur)** pourquoi ne pas faire tous de suite de l'imbriqué ... 
  - ici ça doit ressembler à  ça : 
```java
public Carte joueurJoue(int joueur) throws UnknownPlayer{
		Carte carte;
		if(joueur==1) {
			carte= tasJ1.push(joueur1.joue());
		}else if(joueur==2) {
			carte =tasJ2.push(joueur2.joue());
		}else {
			throw new UnknownPlayer("Joueur inconnu");
		}
		return carte;
	}
```
 - instanciation inutile dans la méthode **derniereCarteJouee(int joueur)**
 - problème itération dans la méthode **printTasJoueur(int joueur)**
 # note : 15/20
