### ISSUE TITLE
TP quincaillerie

### ISSUE THREAD

**Issue by nicomr70** [nicomr70/java-Tom#8]
faire le TP "Gestion d'une quincaillerie".
Attention ce TP est complexe car c'est a doit de comprendre qui dépend de quoi , et quelles sont les informations importantes à avoir

**Comment by nicomr70** [comment]
# Correction du Modèle : 
## Partie Pièces :
### dans le fichier Pieces.java :
- une pièce doit avoir un certain comportement obligatoire et donc la il manque toutes les fonctions abstraites qui te permettent d'être sûr d'un comportement (Comme une interface, mais la dans l'héritage, mais aussi pas faire forcement des getter et des setter mais faire des attribue calculer) ça pourrait ressembler à :  
```java
setDureeGarantie(int dureeGrantie);
getDureeGarantie();
//mais plutôt 
int abstract dureeGarantie();
```
```java
setDureeFabrication(int dureeFabrication);
getDureeFabrication();
//mais plutôt
int abstract dureeFabrication();
```
```java
setPrix(int dureeFabrication);
getPrix()
//mais plutôt
int abstract prix();
```
* Ensuite pourquoi définir ``setRef(String ref)`` dans pièces alors que tu ne connais même pas la référence ? ici dans le modele c'est une fonction qui doit être redéfinie plus tard donc :
```java
void abstract setRef(String ref);
````
### dans le fichier PiecesDeBase.java :
* sur ``setRef(String Ref)`` inutile d'appeler super car comme j'ai dit précédemment, il ne faut pas le définir dans **Pieces.java**
### dans le fichier PiecesComposites.java :
* dans cette classe les attribues ``dureeDeGarantie``et ``dureeDeFabrication``ne te serve à rien car ici tu fait un simple calcul pour les avoir, donc tu n'a pas besoin de les stockés (comme j'ai dit précédemment c'est des attribues calculés ici ) ! 
* ça pourrait ressembler à ça : 
```java
public int DureeGarantieBase() {
		return garBaseComp();
	}
```
* idem pour la duree de fabrication.
### dans le fichier PiecesCompositeEnKit.java :
* comme dans le fichier précédent ici le prix et la duree de garantie sont **calculés** donc les attribues ``prix``et ``dureeGarantie``ne servent à rien, donc pas besoin de définir les fonctions ``garCompKit``et ``prixPiecesCompKit``
### Dans le fichier PiecesCompositeMontee.java :
* donc encore une fois les attribues ``prix``et ``dureeDeGarantie``ne servent à rien car se sont des attribues **calculés**
### Conclusion partie Pieces : 
tu n'a pas pensé que la durée de fabrication, de garantie et le prix sont des attribues tous le temps calculés donc ils non aucune existence en attribues , mais qu'en **méthode** !
## Partie Client : 
### dans le fichier Client.java : 
* ⚠️ ta Map ``piecesPossédees``n'est jamais instancier et n'est jamais utilisée.
### Conclusion : 
ta partie client n'est pas mal du tout mais attention à ne pas mettre des chose inutile , mais surtout **pensez a toujours instancier les structures utilisées**

# Note provisoire : 9 / 12

**Comment by TomFrances** [comment]
Gestion d'une quincaillerie terminée (affichage minimaliste des commandes mais à priori tout est fonctionnel)

**Comment by nicomr70** [comment]
# Correction de l'interface 
##  Remarque générales sur l'utilisation de l'interface
* il manque des accroche sur les focus des fenêtres
* attention les stocks sont très mal gérer niveau interface : 
   - les pièces n'ayant plus de stocks apparaissent dans l'interface client
   - les spinners précisant la quantités disponible devrait être lié au **stock** et faire des range de 0 à 30
   - quelques bug notables avec l'ajout au panier et le stock
* dans les commandes : 
   - il manque beaucoup d'info importante pour une commande : 
      - l'adresse de facturation
      - adresse de livraison
      - etc ...
   - ensuite une commande ne doit pas changer ces informations si le client évolue , donc ici il faut faire une copie **immuable** du client qui passe la commande. (⚠️ ici seul l'adresse de contact ce base sur le client courant !)
  
### Point général de l'interface
* ton application est trop longue a charger car tu reconstruit beaucoup de chose pour rien. (pensez aussi à montrer que l'application charge)
* passage en pleine écran est **impossible** car l'affichage ne suit
* le redimensionnement de la fenêtre pose le même problème.
* il manque beaucoup de fermeture automatique de fenêtre 
* attention au message donnée (souvent pas assez explicite )
* et attention au information écrite sur l'interface (ex : le credit , alors que l'on est pas dans un system a credit pour toi donc ici la compréhension c'est : développeur ✅  mais client 🔴 )

## Remarque générales sur le code
* quand une fonction est identique de partout, il ne faut surtout pas la redéfinir partout ... ici je prend l'exemple de la fonction ```createBtnReturn()``` qui ne devrait être définie une seule fois dans **Application.java** de cette manière : 
```java
 private JPanel createBtnReturn(JFrame retour, Class cl) {
		JPanel pnlBtnReturn = new JPanel(new FlowLayout(FlowLayout.LEFT));
		JButton btnReturn = new JButton(new ImageIcon(new ImageIcon(PATH_TO_ICONS + "return_icon.png").getImage().getScaledInstance(20, 15, Image.SCALE_SMOOTH)));
		btnReturn.addActionListener(ev->{Cl.getMethod("demarrer ",{JFrame.getClass()}).invoke(null,retour)});
		pnlBtnReturn.add(btnReturn);
		return pnlBtnReturn;
	}
```
** Le lien: https://www.it-swarm-fr.com/fr/java/comment-acceder-une-methode-statique-une-reference-de-classe/971884764/ **
* idem pour la variable ```PATH_TO_ICONS``` qui elle est une variable static qui appartient a l'application et non a plusieurs class... ⚠️ ici c'est une grosse erreur car ta variable étant **static** elle devrait être instancié 1 seule fois ! 
* idem avec la fonction ```initUI()``` qui devrait existé 1 seule fois puisqu'elle est **static**
* Il y a plein d'attribue dans tes classes qui pourrai être évités et donc  cela te permettra de mieux gérer les Maj des composants.
* certain bouton devrait avoir une obligation de focus sur la touche entrer (validation de connexion par exemple)
* la fonction ```imagePieces``` appartient a l'application et devrait être défini avec une map contenant le nom de la pieces avec l'image qui est derrière , comme sa ton image est changer qu'une seul fois au démarrage de l'application.

### dans le fichier MenuClientConnexion.java : 
* le tableau de label ne sert rien alors quoi bon le mettre dans la fonction 
```java 	
private JPanel valider(JLabel[] labels, JComponent[] fields);
```
ici ayant un nombre de filles relativement réduits tu aurait tous de suite pu mettre les bon champs donc ça donnerait un truc du style : 
```java
private JPanel valider(JTextField email , JPasswordField pass);
```
comme ça tu évite de faire du casting et donc tu rend plus stable ton application.
* ensuite ton action listener peut être **contracté** pour ton bouton validé.
* ta fonction ```private JPanel inputField(String s) ```vas appartenir a l'application, et non a chaque class.

### dans le fichier MenuClientCatalogue.java :
* tu recréer a chaque changement tout le panel central , ce qui fait que ton application est très **lourdes et longue au chargement**
* tu a gérer le fait que le ** stock soit nul**  sur une pieces avec un autre affichage, mais tu ne le fait qu'une seul fois donc ça ne peux jamais ce remettre a jour, cette partie de code 
```java
		//FIXIT ici pourrait etre mis dans une fonction annexe pour pouvoir maj le panel de la pieces a chaque changement ... 
		//----------------------------------------------------------------//
		if(Application.quincaillerie.getStocks().stocksPiece(piece) == 0) {
			panelPiece.setBorder(BorderFactory.createTitledBorder(null, "INDISPONIBLE", TitledBorder.CENTER, TitledBorder.TOP));
		}else {
			panelPiece.setBorder(BorderFactory.createLineBorder(Color.BLACK));
		}

		//----------------------------------------------------------------//
```
doit être une fonction indépendante, et qui est appelé à chaque fois que tu change le stock d'une pièce.
* ensuite cette ligne ```Application.panier.ajoutPiecePanier(piece,nbValues.getSelectedIndex()+1 );``` ne devrait pas être écrit comme ça mais plutôt comme ça ```(int)nbValues.getSelectedItem();```
* ```ImagePieces```appartient a Application
* ton handler de ton bouton commander fait trop d'action lourdes , c'est pas lui de refaire l'affichage mais plutôt a lui d'appeler la fonction qui vas s'occuper de ça !
* attention ton message de commande refusée n'est pas clair du tout ...

### dans le fichier MenuQuincaillerieCommandes.java
* ici les bouton doivent **ABSOLUMENT évolué** donc au moment ou une commande passe a l'état **livraison** elle ne peut plus être annulé mais être **retourner** et voir même aucun des deux après un certain délai.


## Remarque générale :
* Un TP qui est bien réalisée , mais qui a des soucis majeurs qui aurait été important de régler, et un modélisme presque correct, vraiment certain erreur ou oublie sont assez gros ^^' et vraiment prendre le temps que les interfaces client soit ultra stable ! ici tu a 5 car tu a fait une belle interface mais beaucoup d'erreur et surtout tu a voulu faire la fin à la rache, et je t'vais dit que qu'on livre une application pareil, ici il vaut mieux avoir une application stable avec peut de fonctionnalités qu'une application instable pour ton client et leur client. 


# Note provisoire :  5/8

**Comment by nicomr70** [comment]
# note final :  14/20
